DROP TABLE CLIENTS CASCADE CONSTRAINT;                                          
DROP TABLE LIVRES CASCADE CONSTRAINT;                                           
DROP TABLE ACHATS CASCADE CONSTRAINT;                                           
DROP TABLE AVIS CASCADE CONSTRAINT;                                             
DROP TABLE PERSONNE CASCADE CONSTRAINT;                                         
DROP TABLE FILM CASCADE CONSTRAINT;                                             
DROP TABLE JOUER CASCADE CONSTRAINT;                                            
DROP TABLE CINEMA CASCADE CONSTRAINT;                                           
DROP TABLE PROJECTION CASCADE CONSTRAINT;                                       
