SET ECHO OFF
SPOOL effacerResult.sql
SET ECHO OFF
SET FEEDBACK OFF
SET HEADING OFF
SET PAGESIZE 0
SELECT 'ALTER TABLE ' || table_name || ' DISABLE CONSTRAINT ALL ;'
FROM USER_TABLES ;
SELECT 'DELETE FROM ' || table_name || ';'
FROM USER_TABLES ;
SELECT 'ALTER TABLE ' || table_name || ' ENABLE CONSTRAINT ALL ;'
FROM USER_TABLES ;
SPOOL OFF
SET ECHO ON
