SET ECHO OFF
SPOOL effacerResult.sql
SET ECHO OFF
SET FEEDBACK OFF
SET HEADING OFF
SET PAGESIZE 0
SELECT 'ALTER TABLE Achats DISABLE CONSTRAINT achats_FKcl ;' FROM Achats ;
SELECT 'ALTER TABLE Achats DISABLE CONSTRAINT achats_FKli ;' FROM Achats ;
SELECT 'ALTER TABLE Avis DISABLE CONSTRAINT avis_FKcl ;'  FROM Avis ;
SELECT 'ALTER TABLE Avis DISABLE CONSTRAINT avis_FKli ;'  FROM Avis ;
SELECT 'ALTER TABLE Avis DISABLE CONSTRAINT avis_PK ;'  FROM Avis ;
SELECT 'ALTER TABLE Achats DISABLE CONSTRAINT achats_PK ;'  FROM Achats ;
SELECT 'ALTER TABLE Livres DISABLE CONSTRAINT livres_PK ;'  FROM Livres ;
SELECT 'ALTER TABLE Clients DISABLE CONSTRAINT clients_PK ;'  FROM Clients ;
SELECT 'DELETE FROM ' || table_name || ';'
FROM USER_TABLES ;
SELECT 'ALTER TABLE Avis ENABLE CONSTRAINT avis_PK ;'   FROM Avis ;
SELECT 'ALTER TABLE Achats ENABLE CONSTRAINT achats_PK ;' FROM Achats ;
SELECT 'ALTER TABLE Livres ENABLE CONSTRAINT livres_PK ;'  FROM Livres ;
SELECT 'ALTER TABLE Clients ENABLE CONSTRAINT clients_PK ;'  FROM Clients ;
SELECT 'ALTER TABLE Achats ENABLE CONSTRAINT achats_FKcl ;' FROM Achats ;
SELECT 'ALTER TABLE Achats ENABLE CONSTRAINT achats_FKli ;' FROM Achats ;
SELECT 'ALTER TABLE Avis ENABLE CONSTRAINT avis_FKcl ;'  FROM Avis ;
SELECT 'ALTER TABLE Avis ENABLE CONSTRAINT avis_FKli ;'  FROM Avis ;
SPOOL OFF
SET ECHO ON
